[build]
builder = "NIXPACKS"
buildCommand = "npm install --production"

[deploy]
startCommand = "node src/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 100
